export const AppImages = {
    TextLogo: require('./TextLogo.png'),
    Settings: require('./Settings.png'),
    Settings_White: require('./Settings_White.png'),
    Lock: require('./Lock.png'),
    GetProWithDog: require('./GetProWithDog.png'),
    GetProText: require('./GetProText.png'),
    BeagleSideImage: require('./BeagleSideImage.png'),
    BeagleFrontImage: require('./BeagleFrontImage.png'),
    BeagleSleepingImage: require('./BeagleSleepingImage.png'),
    LeftPolygon: require('./LeftPolygon.png'),
    DownPolygon: require('./DownPolygon.png'),
    DownPolygonTwo: require('./DownPolygonTwo.png'),
    Arrow: require('./Arrow.png'),
    BeagleRightFrontImage: require('./BeagleRightFrontImage.png'),
    Tick: require('./Tick.png'),
    BeagleFullFrontImage: require('./BeagleFullFrontImage.png'),
    ShuffleIcon: require('./ShuffleIcon.png'),
}